### PR TITLE
User class changes and User Storage creation

### PR DESCRIPTION
**Pull request by JugglypuffM**
Added profile fields and their getters with verification to user class. 
Created simple storage class to work with user storage as an object. 
Also made simple unit tests for both of them.

### CODE REVIEW

**Comment by TatianaYuzh** [comment]
I looked at the code, the user's classes are good, I would make an edit in the age range (16-120)

**Comment by JugglypuffM** [comment]
Okay, but the range now is 15-119, so does it worth it to change?

**Comment by TatianaYuzh** [comment]
Okay, let's keep it that way

**Comment by JugglypuffM** [comment]
Any other remarks?

**Comment by TatianaYuzh** [comment]
No, you can merge

**Pull request merged**
