### PR TITLE
 Changed MessageProcessor

### PR DESCRIPTION
**Pull request by TatianaYuzh**
Added auxiliary method, changed the logic of message processing: added new commands handling, profile filing procedure, profile editing procedure and matching procedure. Also added tests.

### CODE REVIEW

**Comment by JugglypuffM** [comment]
Wow... That's huge, why in only one commit?
I'll check it, give me a minute

**Comment by JugglypuffM** [comment]
There are more than one auxiliary methods...
No problems with them though

**Comment by JugglypuffM** [comment]
Main method could've been separated, but it works so doesn't matter

**Comment by JugglypuffM** [comment]
Well, guess you can merge

**Comment by TatianaYuzh** [comment]
Yes, there are several methods here, it was typo
Ok, fine

**Pull request merged**
